//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSVP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurTable
    {
        public long PropId { get; set; }
        public Nullable<int> nCanonId { get; set; }
        public Nullable<System.DateTime> dtReportDate { get; set; }
        public Nullable<int> nTerOtdelenie { get; set; }
        public Nullable<int> nTerPodrazdel { get; set; }
        public Nullable<decimal> vProcent { get; set; }
    }
}
